### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'metrics_tensors'

### ISSUE THREAD

**Issue by PravinVedurla** [vjgpt/Nuclei-Segmentation-using-Mask-RCNN#1]
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
Traceback (most recent call last):
  File "main.py", line 487, in <module>
    train(model, args.dataset, args.subset)
  File "main.py", line 288, in train
    layers='heads')
  File "I:\ML\Projs\Nuclei_project\mrcnn\model.py", line 2355, in train
    self.compile(learning_rate, self.config.LEARNING_MOMENTUM)
  File "I:\ML\Projs\Nuclei_project\mrcnn\model.py", line 2200, in compile
    self.keras_model.metrics_tensors.append(loss)
AttributeError: 'Model' object has no attribute 'metrics_tensors'

I tried downloading the original mrcnn folder from Matterplot's repository but the error persists. , please help me out if possible.

**Comment by PravinVedurla** [comment]
Downgrading Keras to 2.2.5 has resolved the issue. So just try out `pip install keras==2.2.5`
